# Generated by Django 3.1.3 on 2020-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.IntegerField(verbose_name='orderNum')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CartMenu', models.CharField(max_length=50, verbose_name='CartMenu')),
                ('CartQty', models.IntegerField(verbose_name='CartQty')),
                ('CartPrice', models.IntegerField(verbose_name='CartPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='IngrdName')),
                ('qty_base', models.IntegerField(verbose_name='IngrdQtybase')),
                ('qty_now', models.IntegerField(verbose_name='IngrdQtynow')),
                ('price', models.IntegerField(verbose_name='IngrdPrice')),
                ('origin', models.CharField(max_length=50, verbose_name='IngrdOrigin')),
                ('exprtdate', models.DateTimeField(verbose_name='ExprtDate')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=50, verbose_name='MenuName')),
                ('MenuPrice', models.IntegerField(verbose_name='MenuPrice')),
                ('image', models.ImageField(default=None, upload_to='MacKiosk/static/images/')),
                ('category', models.CharField(choices=[('side', 'Side Menu'), ('dessert', 'Dessert'), ('set', 'Set Menu'), ('single', 'Single'), ('drink', 'Drink')], default='single', max_length=30, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNum', models.IntegerField(verbose_name='OrderNum')),
                ('OrderQty', models.IntegerField(verbose_name='OrderQty')),
                ('OrderMenu', models.CharField(max_length=50, verbose_name='OrderMenu')),
                ('OrderDate', models.DateField(verbose_name='OrderDate')),
                ('OrderPrice', models.IntegerField(verbose_name='OrderPrice')),
                ('OrderComplete', models.BooleanField(default=False, verbose_name='CompleteStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50, verbose_name='Content')),
                ('sales', models.IntegerField(blank=True, default=0, verbose_name='Sales')),
                ('spend', models.IntegerField(blank=True, default=0, verbose_name='Spend')),
                ('salesdate', models.DateField(default=0, verbose_name='SalesDate')),
            ],
        ),
    ]
